"""Tilføj audit_score til PageSpeedAudit

Revision ID: 2e48e84239c6
Revises: a823e9ded4bd
Create Date: 2025-06-30 10:37:41.817417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e48e84239c6'
down_revision: Union[str, Sequence[str], None] = 'a823e9ded4bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagespeed_audits', sa.Column('audit_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagespeed_audits', 'audit_score')
    # ### end Alembic commands ###
