"""Add user_id to PageSpeedAnalysis

Revision ID: 6770083a6366
Revises: 2e48e84239c6
Create Date: 2025-07-09 17:55:11.869765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6770083a6366'
down_revision: Union[str, Sequence[str], None] = '2e48e84239c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('pagespeed_analyses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pagespeed_analyses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagespeed_analyses', type_='foreignkey')
    op.drop_column('pagespeed_analyses', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
