"""Tilføj audit_score, description og display_value

Revision ID: a823e9ded4bd
Revises: e3e53c005016
Create Date: 2025-06-30 10:26:49.794085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a823e9ded4bd'
down_revision: Union[str, Sequence[str], None] = 'e3e53c005016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
